# Java
java_version=25

# Gradle
org.gradle.jvmargs=-Xmx2G

# Mod
mod_version=1.10.0
maven_group=hub.lol
archives_base_name=menumusic

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_api_version=0.157.0+26.2
loom_version=1.17-SNAPSHOT
