# NeoForge-specific versions.
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
moddev_version=2.0.148
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[26.2]
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=26.2.0.88
